# Generated by Django 6.0.2 on 2026-02-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_snippet_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='content_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='marker',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
