# Generated by Django 6.0.2 on 2026-03-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_snippet_content_type_snippet_marker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.TextField(blank=True, max_length=20, null=True)),
                ('color', models.TextField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='marker',
        ),
        migrations.AddField(
            model_name='snippet',
            name='in_trash',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snippet',
            name='badges',
            field=models.ManyToManyField(blank=True, to='api.badges'),
        ),
    ]
